### ISSUE TITLE
Re-write the introduction

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#34]
Version 2 will need different context, different signposting, and in general a different introduction than v1. 
Some items to address include: 
 - [x] v1 and v1.1 have different kinds of intros and context. v1 has more decision tree basics. v1.1 has more background on operational and academic related work. Decide which of these to keep; maybe merge and keep both?
 - [x] Add the following to related work: Wang, B., Li, X., de Aguiar, L. P., Menasche, D. S., & Shafiq, Z. (2017). Characterizing and modeling patching practices of industrial control systems. Proceedings of the ACM on Measurement and Analysis of Computing Systems, 1(1), 1-23.
 - [x] Focus less on CVSS, any discussion of it moves to #30 
 - [x]  reflect new section structure (from #95)
 - Focus on what SSVC v2 provides. Do not focus on what SSVC v1 did, or what changes were made. Those go in a separate section, towards the end of the document handled by #122.

**Comment by j---** [comment]
Also need to:
 - [ ] reflect new section structure implied by renaming in #95

**Comment by j---** [comment]
For v2, just call out #35 , but #35 will not be accomplished in v2.

**Comment by cgyarbrough** [comment]
These changes look appropriate. Focus on the current version and move the v1 and 1.1 stuff to the change log in the other section.
