### ISSUE TITLE
Revisting decisions, recursion, and what the remediation action should be

### ISSUE THREAD

**Issue by j---** [CERTCC/SSVC#46]
#5 clarifies that the action resulting from SSVC decisions is not just patch. It is any kind of remediation. (Terms follow https://vuls.cert.org/confluence/display/CVD/4.4+Remediation.) The first set of actions is just to lay out this situation clearly and define some possible actions:
 - [x] add text to explain that SSVC provides a priority with which to act, and not the action to take. (fixed earlier)
 - [x] Define remediation actions for "fix" (probably apply a patch OR change/upgrade the system) (Cite the [DoD Instruction 8531.01](https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/853101p.pdf?ver=2020-09-15-143058-347) and make changes there to align to SSVC as necessary) (fixed earlier)
 - [x] Define "mitigation" (may include change configs, change network configs, disable the service, auditing and detection) (Cite the [DoD Instruction 8531.01]https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/853101p.pdf?ver=2020-09-15-143058-347) and make changes there to align to SSVC as necessary) (fixed earlier)
 - [x] File any issues related to the CVD guide definitions [here](https://github.com/CERTCC/CERT-Guide-to-CVD/issues)
 -- completed by ADH?

The remediation action applied influences what further actions the vulnerability manager should do. That is, there can be a feedback look between actions taken and SSVC decision points. This is not clear in v1. 
 - [x] Describe how SSVC decisions can be used recursively as the situation changes. Changes outside the control of the stakeholder are covered by #29. So this issue is just to talk about changes to the situation based on actions by the stakeholder. There are situations where, for example, you apply new firewall rules and that will change *Exposure*. Such a mitigation may not be a complete fix, but if it changes the priority with which you need to act from *out-of-cycle* to *defer*, then it was still in some sense an end to the current need to attend to the vul.  (Moved to issue #74)
 - [x] For the defined remediation actions, link them to the SSVC decision point that they can influence. (Moved to issue #79)
 - [x] Seek broad feedback on this section, it's potentially confusing and will be hard to write well. (request comments on drafts related to this issue)

The "fix" actions, once completed, should close the vulnerability management case and not invite recursion. This makes applying a patch qualitatively different from completing a remediation. It's unclear the best way to explain or notate this.
 - [x] Describe difference between "fix" and "mitigate" actions related to recursing decisions. (Moved to issue #74)
 - [x] Decide on most accessible method of incorporating "fix" vs "mitigate" into the SSVC decision process. (Moved to issue #76) 
 - [x] Include decision for what type of remediation to apply in the appropriate tree(s). (Moved to issue #77)
 - [x] Where the appropriate decision is "mitigate" use the connection between types of mitigation actions and the SSVC decision points to recommend heuristics about what mitigations may lead to the most efficient risk reduction. (Moved to issue #78)

**Comment by zmanion** [comment]
Some thoughts based on internal SEI discussion, on "when to re-assess."

When information about an SSVC input changes, re-assess.

This covers the initial assessment (I become aware of a vulnerability). Examples include:
* Exploit activity increases
* I change my use of the affected system, changing mission or safety impact
* I change exposure of the system

**Comment by zmanion** [comment]
SSVC helps you decide with what priority to respond to a vulnerability. This response is either Defer or to take some action. We call the action a "work item" (subject to change).

The work item may be equivalent to "remediate." So a non-Defer action is a remediation. There are different type of remediation. A common one is "patch" (update, upgrade) which is (usually) a complete fix, removing the vulnerability. In this sense, applying a complete/patch remediation means no more SSVC re-assessments, because the problem is gone.

Other remediations are somewhat less complete. The vulnerability technically still exists, but is now much harder (maybe impossible) for an attacker to reach. Examples:
* Changing firewall/network access rules (which would trigger an SSVC re-assessment with lower Exposure)
* Changing a configuration to reduce/remove/block access to a vulnerable feature

Time aspect. Such a "less-than-patch" remediation can be temporary or permanent, we should not imply that it is always temporary. Sometimes there are no patches, ever. Some choose not to patch. Some choose mitigation in place of patching. These are all valid choices.

**Comment by zmanion** [comment]
Terminology: I'll propose "remediation" as the work item that SSVC tells someone they need to do with some priority. "Work item" may be up for discussion in a different issue. "Update" is the "full/complete fix that removes the vulnerability. "Patch" and "Upgrade" are more specific than "Update." Not against "Fix" either.

If we need to, "mitigation" might be the umbrella term for "less-than-complete" remediation.

Remediation
* Update (complete fix)
** Patch, upgrade, hotfix, etc
* Mitigation (less-than-complete fix)
** Workaround, config change, firewall change, other external defensive measures

**Comment by zmanion** [comment]
DOD INSTRUCTION 8531.01
DOD VULNERABILITY MANAGEMENT
https://www.esd.whs.mil/Portals/54/Documents/DD/issuances/dodi/853101p.pdf?ver=2020-09-15-143058-347

3.5.  STEP 4: REMEDIATION AND MITIGATION

> Remediation occurs when the vulnerability is eliminated or removed. Mitigation occurs when the impact of the vulnerability is decreased without reducing or eliminating the vulnerability.

So consider this, and keep CVD Guide and SSVC at least in sync.

**Comment by ahouseholder** [comment]
@zmanion Two comments back you specifically suggested that remediation _includes_ mitigation. But that's not what the DoD doc you quoted says.

https://blog.rapid7.com/2020/09/14/vulnerability-remediation-vs-mitigation-whats-the-difference/ also takes the same def'n as the DoD doc.

So if we go with remediation as inclusive of both fixes and mitigation,  then we will be misaligned with that usage.

**Comment by j---** [comment]
In the CVD guide, remediation includes mitigation. https://vuls.cert.org/confluence/display/CVD/4.4+Remediation
SSVC should follow the CVD guide so we are internally consistent.
Currently there is no CVD guide issue to change these terms (https://github.com/CERTCC/CERT-Guide-to-CVD/issues). If there is one, link it here please. But until then, my expectation is that we will note that SSVC terms are in conflict with these external terminology uses, and that is OK as long as we're clear about it. 
Is someone arguing against this?

**Comment by ahouseholder** [comment]
This is a situation where I think the guide may be in error because it is based on a CERT/CC colloquial usage that appears to be out of sync with a more common definition. I didn't go looking for definitions of terms before we started writing it, nor was it given the kind of scrutiny we are currently applying to SSVC v2. I'd rather have SSVC leapfrog the CVD guide (anticipating it to be eventually consistent) with the right target than simply taking what we wrote down in the guide in 2017 just because we wrote it down.

**Comment by zmanion** [comment]
OK, so an SSVC work item is, $something, not sure of the term yet, so I'll use "work item" here.

SSVC helps you decide the priority with which to perform take some action, a work item. Special case is Defer.

Once you've decided priority, you next decide what to do. Remediation is complete removal of the vulnerability, Mitigation is less than Remediation.

Mitigation can be temporary or "permanent," we can discuss that it is often, but not necessarily temporary (e.g., until remediation is available and can be applied).

* work item
  * defer
  * act
    * remediation
      * fix, patch, update, upgrade
      * remove vulnerable software/system
    * mitigation
      * config change, firewall/access change

**Comment by laurie-tyz** [comment]
This is what I'm thinking:

    defer
         Permanent
         Temporary – recursion of decision tree
    act
        remediation
            fix, patch, update, upgrade
            remove vulnerable software/system
        mitigation
            config change, firewall/access change

comments?

**Comment by ahouseholder** [comment]
@laurie-tyz I don't think any deferral is permanent. Or rather, permanence is an illusion -- you can always decide to do something else in the future as long as there remains a deployed vulnerable system.

That said, I do think there is room for subtlety in _defer_, and that might be captured by accommodating a re-evaluation trigger event. Triggers might be time-based (reconsider in 2 weeks) or or event based (no patch available today, reconsider when patch available).

One way to approach this too could be something like this:

- Remediation fixes the problem (removes the vulnerability from deployed systems). 

- Mitigation's goal might be to cause an immediate reevaluation of the tree to reduce the priority of response remaining. E.g., by reducing exposure, changing attacker utility (either automatability or value density), or reducing safety or mission impacts. An ideal mitigation reduces the reevaluation to defer.

- "Defer" results should make note of what events could trigger re-evaluation (time or event triggers as above)

**Comment by j---** [comment]
Closing this issue because the relevant remaining TODOs now have their own issues that can be tracked separately.

**Comment by zmanion** [comment]
> OK, so an SSVC work item is, $something, not sure of the term yet, so I'll use "work item" here.

Proposal that $someting = "response activity" see #32.
